name: "InstantDb Server Build Image"

on:
  workflow_dispatch: {}
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/server-build-image.yml
      - server/**
  # pull_request:
  #   branches:
  #     - "main"
  #   paths:
  #     - .github/workflows/server-build-image.yml
  #     - server/**

concurrency:
  group: server-image-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Version
        run: |
          version=`date "+%y%m%d%H%M"`
          echo "VERSION_SEMVER_FULL=$version"
          echo "VERSION_SEMVER_FULL=$version" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to AWS Container Registry
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password \
            --region ${{ secrets.AWS_CONTAINER_REPO }} | \
            docker login \
            --username AWS \
            --password-stdin \
            ${{ secrets.AWS_CONTAINER_REPO }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: server
          push: true
          provenance: false
          tags: |
            "ghcr.io/chris-garrett/instant:${{ env.VERSION_SEMVER_FULL }}"
            "${{ secrets.AWS_CONTAINER_REPO }}/instant:${{ env.VERSION_SEMVER_FULL }}"
            ${{ github.ref == 'refs/heads/main' && format('{0}:latest', 'ghcr.io/chris-garrett/instant') || '' }}
          labels: |
            org.opencontainers.image.source="https://github.com/chris-garrett/instant"
            org.opencontainers.image.title="InstantDb Server"
            org.opencontainers.image.version="${{ env.VERSION_SEMVER_FULL }}"
            org.opencontainers.image.created="{ver.timestamp}"
            org.opencontainers.image.revision="${{ env.VERSION_SEMVER_FULL }}"
            org.opencontainers.image.branch="${{ github.ref }}"
